### ISSUE TITLE
[warn] [flic] TypeError: Cannot read property 'build' of null

### ISSUE THREAD

**Issue by ukmoose** [hardillb/node-red-contrib-flic-buttons#1]
Hi Ben,

So I have installed bluez and the flic lib, I have the demon running and I can pair the buttons using the flic command so I am assuming the install of the libraries went OK.  

I have the bluetooth demon running (sudo ./bluetoothd -nEd)
and the flic demon running (~/bluetooth/flic/armv6l $ sudo ./daemon -l -f flic.sqlite3)
Both of which are very "chatty"
(I'm using the third beta of the flic distribution)

But when I start nodered having installed the nodes I get the following...

30 Jan 14:41:53 - [info] Loading palette nodes
30 Jan 14:42:03 - [warn] ------------------------------------------
30 Jan 14:42:03 - [warn] [flic] TypeError: Cannot read property 'build' of null
30 Jan 14:42:03 - [warn] ------------------------------------------
30 Jan 14:42:03 - [info] Settings file  : /home/pi/.node-red/settings.js

any ideas?  

Node-RED version: v0.12.5
Node.js  version: v4.2.4
Pi 2 - Using armv6 because of https://github.com/50ButtonsEach/fliclib-linux-dist/issues/9 - will try again with armv7 tomorrow..

rgds

Mark

**Comment by hardillb** [comment]
That error implies that it can't find the protobuf library in the underlying node-flic-buttons npm

Have a look in the nested node_modules directory to see if everything is there

**Comment by ukmoose** [comment]
Thanks of the quick response!

No I've checked the nested node_modules and its there.
e..g. ~/.node-red/node_modules/node-red-contrib-flic-buttons/node_modules/node-flic-buttons/node_modules/protobufjs

No errors when I installed it...

pi@raspberrypi:~/.node-red $ npm i node-red-contrib-flic-buttons
node-red-contrib-flic-buttons@0.0.4 node_modules/node-red-contrib-flic-buttons
└── node-flic-buttons@0.0.4 (protobufjs@4.1.3)

I'll have another go tomorrow.
