### ISSUE TITLE
error in readme

### ISSUE THREAD

**Issue by LipJ01** [hardillb/node-red-contrib-flic-buttons#10]
instead of /bin/armv61/

it's actually (based on install on latest jessie update with fresh pi) /home/pi/fliclib-linux-hci/bin/armv6l/

notice it's an L (lower case) not a 1... i've been caught out by it before so knew to change it. why? who knows... but it's an l.

**Comment by hardillb** [comment]
It stands for little endian because Arm CPUs can be either. I'll fix it
