### ISSUE TITLE
Couldn't open log file: Permission denied

### ISSUE THREAD

**Issue by xaliander** [hardillb/node-red-contrib-flic-buttons#12]
The rc.local must include a sudo for the command to run without error.

sleep 10 && sudo /home/pi/git/fliclib-linux-hci/bin/armv6l/./flicd -d -l /var/log/flic.log -f /home/pi/git/fliclib-linux-hci/bin/armv6l/flic.sqlite3 &

**Comment by xaliander** [comment]
Am I wrong? A little feedback would be awesome if so. Thanks!

**Comment by hardillb** [comment]
I couldn't see a question or enough detail for a proper bug rey, but rc.local should run as root, so no you shouldn't need sudo

And even if so this would be a big again the flic code not here

**Comment by xaliander** [comment]
Okay my bad then. In the readme of node-red-contrib-flic-buttons right after "Add the following line just before the exit 0:" you mention the command without sudo. If I call this command I get the mentioned error.
Adding sudo as above solved my issue at startup.
Cheers
