### ISSUE TITLE
Flic 2 support

### ISSUE THREAD

**Issue by gobo-ws** [hardillb/node-red-contrib-flic-buttons#15]
Flic 2 support been added to the official Linux SDK.
https://github.com/50ButtonsEach/fliclib-linux-hci

Would it been possible to support Flic 2 in the future?
Thanks!

**Comment by hardillb** [comment]
I don't have any Flic 2 devices to looks at this and @Roaders hasn't really had time to look at some of the other feature request.

I can look at any pull requests to add this.

**Comment by gobo-ws** [comment]
Thanks for the answer. I got a Flic 2 yesterday, hopefully I have time to have a look on it within a couple of weeks.

**Comment by gobo-ws** [comment]
I haven't had time to delve into what API changes that has been made but I can confirm that this node still works with the new Flic 2 button.
