### ISSUE TITLE
Why add buttons by device ID?

### ISSUE THREAD

**Issue by njh** [hardillb/node-red-contrib-flic-buttons#4]
Hello,

I am delighted that this node exists - once I got bluetooth/flicd working it was very quick to start receiving events in Node-RED.

However one thing I am not clear about - why do you have to enter/register button device IDs in the Node-RED UI - why not just list the available buttons already registered with flicd?

Assigning a button name to the device id is useful for tracking buttons (actually, it is a shame this isn't done in flicd) but why isn't this this output in the message?

nick.

**Comment by hardillb** [comment]
Because to be honest I got a minimum viable solution working with the first version of the linux library they produced then lost interest in flic buttons. They don't have the range I need for the solution I was looking to implement.

@Roaders has updated the node to work with the new stuff, you'll need to check with him for the second version of the Linux library

**Comment by njh** [comment]
Ok, cool, thanks.

I have a Raspberry Pi in the centre of my loft that seems to provide good coverage for the upstairs of my house.

I may submit some improvement PRs then...

**Comment by Roaders** [comment]
I had plans and started implementing displaying a list of already registered buttons in the node but never got round to finishing it. I was waiting for 0.14 to be released as this allows config nodes to have config nodes which makes implementing this easier (you have a flic daemon config node and then have a flic button config node that ties a button name to a bd address that you pick from a drop down).

**Comment by njh** [comment]
That is one of the reasons why I raised 50ButtonsEach/fliclib-linux-hci#27, so that the name/button id mapping can take place in flicd.

That way, you only need a flic daemon config node, and can then just choose a button name in a drop down list - rather than having to do that in Node-RED.
